### ISSUE TITLE
SQ-1000 Assignment only to tracked aircrafts (automatic)

### ISSUE THREAD

**Issue by MikeW27** [pierr3/ModeS#2]
Hello
Your plugin is very usefull for vACC's who are using SQ1000, but it's also extremly anoying to those who doesn't. In Switzerland we do not use SQ1000 and get it assigned all the time as DEL.
Could you please reduce the automatic function to modify only "tracked by myself" airplanes?
That would help us a lot.
Or at least build in a LAT/LON filter to only assign SQ1000 to aircrafts which are in a certain area (eg LF-Airspace).
Thank you very much, best regards
Mike

**Comment by pierr3** [comment]
Hi,

No problem, i'm removing Switzerland from the auto assignment list, the plugin should be updated soon to avoid those problems anyway.

Pierre
